ss-67: Add API to create, update and delete categories
BinaryStudioAcademy/bsa-winter-2022-2023-smartspend pull request #121
Opened 2023-03-22 19:57 UTC by teslmik

![Postman_SLuUmyP01W](https://user-images.githubusercontent.com/16450566/227022273-06762b36-82c0-4870-91e5-d07d2a59bc41.png)
![Postman_oenLK9f7KI](https://user-images.githubusercontent.com/16450566/227022302-485b669b-bf4d-4daa-a263-912f581449bb.png)
![Postman_kO6GBKP32g](https://user-images.githubusercontent.com/16450566/227022320-4049b16e-90e1-4099-95dc-e119496adffc.png)

2023-03-23 09:06 UTC, nikita-remeslov requested changes

2023-03-23 10:26 UTC, teslmik commented on backend/src/common/interfaces/service.interface.ts
> +    delete(id: number): Promise<T>;
because I have an update and delete in the service take arguments, but in the original version there are no arguments

2023-03-23 10:26 UTC, teslmik commented on backend/src/common/interfaces/repository.interface.ts
> +    delete(parameter: string | number): Promise<T>;
because I have an update and delete in the repository take arguments, but in the original version there are no arguments

2023-03-24 18:41 UTC, Evcat6 commented
I think delete request should return boolean type

2023-03-27 07:47 UTC, VItaliy-Kalenichenko commented
> I think delete request should return boolean type

Or removed item data

2023-03-27 08:44 UTC, teslmik commented
> > I think delete request should return boolean type
> 
> Or removed item data

I thought it would be possible then to immediately reward categories except the remote

2023-03-29 06:40 UTC, VItaliy-Kalenichenko commented on backend/src/migrations/20230322112733_add_categories_table.ts
> +        .dropTableIfExists(CATEGORIES_TABLE_NAME)
Why do you drop these tables? You can edit them

2023-03-30 16:27 UTC, Evcat6 approved these changes

2023-03-30 22:23 UTC, nikita-remeslov approved these changes

2023-03-30 22:23 UTC, merged