Fix/ss 152 wrong layout on screen
BinaryStudioAcademy/bsa-winter-2022-2023-smartspend pull request #164
Opened 2023-03-25 21:06 UTC by teslmik

![IPgW2cpcgo](https://user-images.githubusercontent.com/16450566/227741932-d22e4274-7559-40a4-ad3d-c008d1102f8b.png)
![bCWLetxhUH](https://user-images.githubusercontent.com/16450566/227741935-fcc1c963-5d7b-45ff-a41b-cf62f8bcf059.png)
![yfgR8Zp0SB](https://user-images.githubusercontent.com/16450566/227741937-e046cbdb-1733-4b62-85ba-ebfffd764e62.png)
![dHcXQZe8Hr](https://user-images.githubusercontent.com/16450566/227741940-25db1b3a-ef30-4228-9756-2b189d080bb6.png)
![j06oNHKNpA](https://user-images.githubusercontent.com/16450566/227741942-3608392b-75e5-4474-b8a8-d89653dd518e.png)
![x8PNhNcewE](https://user-images.githubusercontent.com/16450566/227741947-a5d25c6c-0f59-4722-837c-157e2073a8be.png)

2023-03-27 10:16 UTC, nikita-remeslov commented
Please add screenshots to PR, not to the issues

2023-03-29 06:12 UTC, nikita-remeslov requested changes

2023-03-29 06:12 UTC, nikita-remeslov commented on frontend/src/assets/css/variables/container-width-variables.scss
can we make a global class to use container size?
```scss
.container {
    max-width: var(--container);
    width: 100%;
}
```

2023-03-29 09:30 UTC, nikita-remeslov commented on frontend/src/bundles/landing/components/footer/footer.tsx
> +    ] as unknown as { to: ValueOf<typeof AppRoute>; value: string }[];
wrong type. It is not AppRoute

2023-03-29 09:34 UTC, teslmik commented on frontend/src/bundles/landing/components/footer/footer.tsx
> +    ] as unknown as { to: ValueOf<typeof AppRoute>; value: string }[];
edit in another issue

2023-03-29 11:31 UTC, nikita-remeslov approved these changes

2023-03-29 11:31 UTC, merged