ss-213: Connect wallets in dashboard to backend
BinaryStudioAcademy/bsa-winter-2022-2023-smartspend pull request #242
Opened 2023-03-31 08:20 UTC by teslmik

2023-04-02 09:33 UTC, teslmik commented on frontend/vite.config.ts
>                              options: {
if you do not change this parameter, then the request to the server goes only when clearing the cache (Ctrl + Shift + R)

2023-04-03 10:04 UTC, nikita-remeslov commented
I think you should merge develop in this PR. Because it contains a lot changes from other task

2023-04-05 06:44 UTC, nikita-remeslov requested changes
Discussed

2023-04-06 08:33 UTC, nikita-remeslov requested changes

2023-04-06 22:45 UTC, VItaliy-Kalenichenko commented on frontend/src/bundles/common/components/header/header.tsx
> +                            <Tabs
It would be better to create a route for this component

2023-04-06 22:46 UTC, VItaliy-Kalenichenko commented on frontend/src/bundles/common/components/header/header.tsx
> +                            `${AppRoute.WALLET}/${id}${AppRoute.TRANSACTION}` && (
It would be better to create a route for this component instead of this condition

2023-04-07 06:28 UTC, nikita-remeslov commented
Conflicts

2023-04-07 08:19 UTC, nikita-remeslov approved these changes

2023-04-07 08:19 UTC, merged