Task/ss 3 add base page
BinaryStudioAcademy/bsa-winter-2022-2023-smartspend pull request #26
Opened 2023-03-14 09:36 UTC by ValeriiArt

added the 'base' component to index.ts.

2023-03-14 12:25 UTC, nikita-remeslov requested changes
Please check task requirements. We don't need to render UI elements at the root route

2023-03-14 13:19 UTC, ValeriiArt commented
route - /ui

2023-03-14 15:04 UTC, nikita-remeslov requested changes

2023-03-14 15:04 UTC, nikita-remeslov commented on frontend/src/bundles/common/enums/styleguide-route.enum.ts
> +const StyleGuide = {
Add your route to `app-route.enum.js`

2023-03-15 07:37 UTC, nikita-remeslov approved these changes

2023-03-15 07:40 UTC, merged