ss-281: Visual defects on the Account settings page
BinaryStudioAcademy/bsa-winter-2022-2023-smartspend pull request #309
Opened 2023-04-05 10:10 UTC by MstyslavDmytryk

2023-04-05 12:25 UTC, anton-otroshchenko approved these changes

2023-04-05 14:22 UTC, Holovashcenko submitted a review, later dismissed

2023-04-05 14:22 UTC, Holovashcenko commented
Resolve conficts

2023-04-05 14:30 UTC, Evcat6 commented
Resolve conflicts

2023-04-05 14:31 UTC, Evcat6 requested changes
In general Looks but resolve conflicts

2023-04-05 15:22 UTC, Evcat6 approved these changes

2023-04-05 19:58 UTC, anton-otroshchenko approved these changes

2023-04-06 07:06 UTC, Holovashcenko approved these changes

2023-04-06 07:07 UTC, merged