ss-14: Add Base Migrations
BinaryStudioAcademy/bsa-winter-2022-2023-smartspend pull request #35
Opened 2023-03-15 06:57 UTC by vasylpopovych

За комітом(1ea9640) "ss-14: * type of field with reference key, which contains id" - змінив типи ключів, на відмінні від тих що вказані в структурі. Інакше при міграції була помилка з імплементацією ключів.

2023-03-15 15:57 UTC, nikita-remeslov submitted a review, later dismissed
Looks good to me
@VItaliy-Kalenichenko What are you think?

2023-03-15 22:21 UTC, VItaliy-Kalenichenko commented
1. You should drop 'users' table and create it again with id of type uuid (use dropTableIfExists method)
2. I think it would be better to have all the migrations in one file, named InitialStructure

2023-03-16 16:50 UTC, vasylpopovych commented
--

2023-03-16 20:04 UTC, nikita-remeslov commented
> I added all migration to one file initial_structure. But have a problem. When try to run migration got the error. I think this error because something wrong in initial_structure file, but unfortunately I can't understand the reason.

Can you provide the error?

2023-03-16 20:29 UTC, nikita-remeslov requested changes
Example 
![image](https://user-images.githubusercontent.com/78347072/225745074-9d692ec3-a4ee-4ec4-99da-ea920c7e88b7.png)

Also, we should down all table in reverse order

2023-03-16 20:29 UTC, nikita-remeslov commented on backend/src/migrations/20230215152530_add_users_table.ts
We never change the existing migration

2023-03-17 12:58 UTC, nikita-remeslov requested changes
Discussed in Slack

2023-03-17 13:47 UTC, nikita-remeslov approved these changes

2023-03-17 13:47 UTC, merged