ss-10: Add Line Chart
BinaryStudioAcademy/bsa-winter-2022-2023-smartspend pull request #38
Opened 2023-03-15 13:07 UTC by Gandrejko

![image](https://user-images.githubusercontent.com/71260645/225317679-cb6930d5-74e9-4803-813e-3b3577090c6d.png)

2023-03-15 16:06 UTC, nikita-remeslov commented
Conflicts

2023-03-15 22:29 UTC, nikita-remeslov requested changes

2023-03-15 22:29 UTC, nikita-remeslov commented on frontend/src/bundles/common/components/charts/line-chart/line.type.ts
Please check project structure 
![image](https://user-images.githubusercontent.com/78347072/225457396-49f78845-3bf6-4f37-b8f6-c56f0896dccd.png)

2023-03-15 22:29 UTC, nikita-remeslov commented on frontend/src/bundles/common/components/charts/line-chart/chart.module.css
styles.module.scss

2023-03-15 22:29 UTC, nikita-remeslov commented on frontend/src/bundles/common/components/charts/line-chart/line.type.ts
Also props type define in the component

2023-03-16 07:54 UTC, Gandrejko commented on frontend/src/bundles/common/components/charts/line-chart/chart.module.css
fixed

2023-03-16 07:54 UTC, Gandrejko commented on frontend/src/bundles/common/components/charts/line-chart/line.type.ts
fixed

2023-03-17 09:07 UTC, Gandrejko commented
https://www.loom.com/share/22d8a6bda824492f94818184b5559619

2023-03-17 12:58 UTC, nikita-remeslov approved these changes

2023-03-17 12:59 UTC, merged