ss-327: add ability to create transaction
BinaryStudioAcademy/bsa-winter-2022-2023-smartspend pull request #395
Opened 2023-04-09 11:45 UTC by Gandrejko

2023-04-09 12:22 UTC, anton-otroshchenko submitted a review, later dismissed

2023-04-09 15:21 UTC, Evcat6 commented
Conflicts

2023-04-10 10:48 UTC, anton-otroshchenko approved these changes

2023-04-10 11:33 UTC, teslmik commented
![chrome_a3XtuLaZm2](https://user-images.githubusercontent.com/16450566/230893888-a0bce880-c772-433e-a830-7cb32f2251d3.gif)

2023-04-10 13:53 UTC, Evcat6 requested changes

2023-04-10 13:53 UTC, Evcat6 commented on frontend/src/bundles/common/components/transaction-modal/transaction-image.tsx
> +        <button
Can we use there our common components?

2023-04-10 13:53 UTC, Evcat6 commented on frontend/src/bundles/common/pages/budgets/budget-details/budget-details.tsx
> +        let spentResult = 0;
i think this should be helper

2023-04-10 13:53 UTC, Evcat6 commented on frontend/src/bundles/common/pages/budgets/budget-details/budget-details.tsx
> +        let spentResult = 0;
maybe `getSpent` or something like this

2023-04-10 17:24 UTC, Evcat6 approved these changes

2023-04-10 19:27 UTC, anton-otroshchenko approved these changes

2023-04-10 19:28 UTC, merged