ss-16: + double rande slider
BinaryStudioAcademy/bsa-winter-2022-2023-smartspend pull request #45
Opened 2023-03-15 16:43 UTC by MstyslavDmytryk

2023-03-15 22:45 UTC, nikita-remeslov requested changes
You should add this component to `/ui` page

2023-03-15 22:45 UTC, nikita-remeslov commented on frontend/src/bundles/common/components/range-slider/range-slider.module.scss
styles.module.scss

2023-03-15 22:45 UTC, nikita-remeslov commented on frontend/src/bundles/common/components/range-slider/range-slider.tsx
> +    onChange?: (filteredData: FinanceOperation[]) => void;
```suggestion
    onChange?: (filteredData: {amount: number}[]) => void;
```

2023-03-15 22:45 UTC, nikita-remeslov commented on frontend/src/bundles/common/components/range-slider/range-slider.tsx
> +}
```suggestion
```

2023-03-16 21:25 UTC, VItaliy-Kalenichenko commented on frontend/src/bundles/common/components/range-slider/range-slider.tsx
> +    const [range, setRange] = useState([rangeLimits.min, rangeLimits.max]);
I think this state is redundant. You will have the same in the parent component.
So you have to add another prop, named like currentRange

2023-03-16 21:26 UTC, VItaliy-Kalenichenko commented on frontend/src/bundles/common/components/range-slider/range-slider.tsx
> +    rangeLimits?: { min: number; max: number };
Move rangeLimits, and onChange args types to a separate interface

2023-03-16 21:31 UTC, VItaliy-Kalenichenko commented on frontend/src/bundles/common/components/range-slider/range-slider.tsx
> +        borderColor: 'var(--color-pink-100)',
I would rather create one 'styles' object with trackStyle and handleStyle. But I don't insist, so it's up to you

2023-03-20 10:25 UTC, MstyslavDmytryk commented
![slider](https://user-images.githubusercontent.com/102343264/226312751-14f21ec1-821f-4bcc-a887-19e736b791a6.png)

2023-03-21 08:35 UTC, nikita-remeslov commented on frontend/src/bundles/common/components/range-slider/range-slider.tsx
> +interface RangeLimits {
Not resolved

2023-03-21 08:35 UTC, nikita-remeslov commented on frontend/src/bundles/common/components/range-slider/range-slider.tsx
> +interface RangeSliderProperties {
Not resolved

2023-03-21 11:01 UTC, nikita-remeslov requested changes

2023-03-21 16:26 UTC, anton-otroshchenko approved these changes

2023-03-22 07:09 UTC, VItaliy-Kalenichenko approved these changes

2023-03-23 09:15 UTC, merged