ss-391:  Create new wallet modal doesn't match the design on the dashboard page
BinaryStudioAcademy/bsa-winter-2022-2023-smartspend pull request #483
Opened 2023-04-11 13:56 UTC by Holovashcenko

![image](https://user-images.githubusercontent.com/41539597/231185911-ec2edda6-03c8-4f4a-9a65-276f8b634f2d.png)

2023-04-11 16:06 UTC, Evcat6 requested changes

2023-04-11 16:06 UTC, Evcat6 commented on frontend/src/bundles/common/components/modal-add-wallet/modal-add-wallet.tsx
> +        balance: '' as unknown as number,
why we have there string but use `as number`?

2023-04-12 06:23 UTC, Evcat6 approved these changes

2023-04-12 13:12 UTC, anton-otroshchenko approved these changes

2023-04-12 13:12 UTC, merged