ss-428: Update filter on dashboard page find by wallet with wallet
BinaryStudioAcademy/bsa-winter-2022-2023-smartspend pull request #501
Opened 2023-04-11 19:06 UTC by Holovashcenko

2023-04-12 20:46 UTC, Holovashcenko commented
![image](https://user-images.githubusercontent.com/41539597/231580917-cc1754ca-2a90-41a5-a56d-e6e93f2ed410.png)

2023-04-13 05:57 UTC, Evcat6 requested changes

2023-04-13 05:57 UTC, Evcat6 commented on frontend/src/bundles/common/pages/dashboard/dashboard.tsx
> +    for (const transaction of transactions) {
we can create for this helper

2023-04-13 05:57 UTC, Evcat6 commented on frontend/src/bundles/common/pages/dashboard/dashboard.tsx
> +// const tabsDashboard = [
does we need this in future

2023-04-13 05:57 UTC, Evcat6 commented on frontend/src/bundles/common/pages/dashboard/dashboard.tsx
> +    // const [firstTabs, setFirstTabs] = useButtonTabsState(tabsDashboard);
same question

2023-04-13 05:57 UTC, Evcat6 commented on frontend/src/bundles/common/pages/dashboard/dashboard.tsx
> +                                    // controls={
same question

2023-04-13 14:35 UTC, Holovashcenko commented
![image](https://user-images.githubusercontent.com/41539597/231793682-9618f51e-4fbe-4fe6-8eaa-481d8f94f397.png)
![image](https://user-images.githubusercontent.com/41539597/231793719-c8a00643-f2b8-4755-bcdf-3525d6f31e0c.png)
![image](https://user-images.githubusercontent.com/41539597/231793765-3ab6b5de-f7c3-4a6a-95aa-9f341dea7d39.png)

2023-04-13 14:36 UTC, Holovashcenko commented on frontend/src/bundles/common/pages/dashboard/dashboard.tsx
> +// const tabsDashboard = [
removed

2023-04-13 15:01 UTC, nikita-remeslov approved these changes

2023-04-13 15:01 UTC, merged