ss-40: Add wallet details page
BinaryStudioAcademy/bsa-winter-2022-2023-smartspend pull request #78
Opened 2023-03-17 19:13 UTC by anton-otroshchenko

2023-03-17 19:15 UTC, anton-otroshchenko commented
![image](https://user-images.githubusercontent.com/105710998/225998557-0a9f0021-723a-4dd6-aef1-96ee5c417ab0.png)
Пока что выглядит вот так, я правда еще никакого адаптива не добавлял, если скажете то на выходных добавлю и еще снизу там должны быть категории, но я пока что их тоже не делал

P.S. заранее извиняюсь если придется много исправлять я с версткой не особо дружу)

2023-03-17 19:18 UTC, anton-otroshchenko commented
Еще кнопки не стилизованы потому что там переменные поменялись, надо поменять переменные в кнопках

2023-03-19 15:58 UTC, teslmik submitted a review, later dismissed

2023-03-20 07:22 UTC, nikita-remeslov reviewed
Please, use English in the PR

2023-03-20 07:25 UTC, nikita-remeslov requested changes

2023-03-20 07:25 UTC, nikita-remeslov commented on frontend/src/bundles/common/pages/wallet-details/styles.module.scss
> +@media only screen and (max-width: 1200px) {
use variables

2023-03-20 07:25 UTC, nikita-remeslov commented on frontend/src/bundles/common/pages/wallet-details/styles.module.scss
> +    .headerContainer {
`.headerContainer, .walletTransactionsContainer`

2023-03-20 07:25 UTC, nikita-remeslov commented on frontend/src/bundles/common/enums/app-route.enum.ts
> +    WALLET_DETAILS: '/wallet-details',
`wallet/:id`

2023-03-20 09:23 UTC, anton-otroshchenko commented
![image](https://user-images.githubusercontent.com/105710998/226297456-cd0ac3b4-2a0d-4448-b2fa-d79691cfba9e.png)
In order to make card bigger we should change the card width in card component later

2023-03-20 09:24 UTC, anton-otroshchenko commented
I didnt use variables for media because they don't work for us

2023-03-21 08:28 UTC, merged